# Generated by Django 3.2.13 on 2022-06-11 15:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('price', models.IntegerField(null=True)),
                ('parentId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.category')),
            ],
        ),
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField(null=True)),
                ('date', models.DateTimeField()),
                ('parentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.category')),
            ],
        ),
    ]
