# Generated by Django 3.2.13 on 2022-06-13 19:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('price', models.IntegerField(null=True)),
                ('type', models.CharField(max_length=20)),
                ('parentId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapi.itemmodel')),
            ],
        ),
    ]
