# Generated by Django 3.2.13 on 2022-06-13 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_itemmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productitem',
            name='parentId',
        ),
        migrations.AddField(
            model_name='itemmodel',
            name='price_is_actual',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='ProductItem',
        ),
    ]
