# Generated by Django 3.2.13 on 2022-06-13 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_auto_20220613_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemmodel',
            name='price_is_actual',
        ),
    ]
