# Generated by Django 3.2.13 on 2022-06-14 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0005_alter_itemmodel_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('price_date_stamp', models.DateTimeField()),
                ('itemId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.itemmodel')),
            ],
        ),
    ]
