# Generated by Django 3.2.13 on 2022-06-14 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0006_pricehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricehistory',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
