# Generated by Django 3.2.13 on 2022-06-14 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0007_alter_pricehistory_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmodel',
            name='children_count',
            field=models.IntegerField(default=0),
        ),
    ]
