# Generated by Django 3.2.13 on 2022-06-14 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0008_itemmodel_children_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemmodel',
            name='children_count',
        ),
    ]
