# Generated by Django 3.2.13 on 2022-06-15 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0009_remove_itemmodel_children_count'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pricehistory',
            unique_together={('itemId', 'price', 'price_date_stamp')},
        ),
    ]
