# Generated by Django 3.2.13 on 2022-06-15 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0010_alter_pricehistory_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmodel',
            name='parentId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='myapi.itemmodel'),
        ),
    ]
