# Generated by Django 3.2.13 on 2022-06-15 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0012_album_track'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='track',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='track',
            name='album',
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='Track',
        ),
    ]
