# Generated by Django 3.2.13 on 2022-06-17 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0013_auto_20220615_2047'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryPrice',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myapi.itemmodel')),
                ('category_items_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='itemmodel',
            name='parentId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='myapi.itemmodel'),
        ),
    ]
