# Generated by Django 3.2.13 on 2022-06-17 20:57

from django.db import migrations, models
import django.db.models.deletion
import myapi.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0016_auto_20220617_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmodel',
            name='price_info',
            field=models.OneToOneField(auto_created=True, default=myapi.models.PriceCalculation, on_delete=django.db.models.deletion.CASCADE, to='myapi.pricecalculation'),
        ),
    ]
