# Generated by Django 3.2.13 on 2022-06-17 21:03

from django.db import migrations, models
import django.db.models.deletion
import myapi.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0017_alter_itemmodel_price_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmodel',
            name='price_info',
            field=models.OneToOneField(auto_created=True, default=myapi.models.get_default_price_model, on_delete=django.db.models.deletion.CASCADE, to='myapi.pricecalculation'),
        ),
    ]
