# Generated by Django 3.2.13 on 2022-06-18 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0018_alter_itemmodel_price_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmodel',
            name='date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='price_date_stamp',
            field=models.DateTimeField(db_index=True),
        ),
    ]
