# Generated by Django 3.2.13 on 2022-06-18 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0019_auto_20220618_0836'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pricehistory',
            unique_together={('itemId', 'price_date_stamp')},
        ),
    ]
