version: '3.8'

services:
  web:
    build:
      context: ./yandexProducts
      dockerfile: Dockerfile.prod
    command: gunicorn yandexProducts.wsgi:application --bind 0.0.0.0:8000
    restart: always
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db

  nginx:
    restart: always
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - web

  db:
    restart: always
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db

volumes:
  postgres_data: